import {
  XCircleIcon,
  PlusCircleIcon,
  MapPin,
  ChevronRight,
  Loader2,
  CarIcon,
  ArrowLeftIcon,
  LocateOffIcon,
  MoveUpIcon,
  MoveDownIcon,
  CornerUpLeftIcon,
  CornerUpRightIcon,
  MoveUpLeftIcon,
  MoveUpRightIcon,
  IterationCwIcon,
  SplitIcon,
  HomeIcon,
  ArrowDownUpIcon,
  MoveUpLeft,
  MoveUpRight,
  Undo2Icon,
} from 'lucide-react';

export const Icons = {
  XCircleIcon,
  PlusCircleIcon,
  MapPin,
  ChevronRight,
  Loader2,
  CarIcon,
  ArrowLeftIcon,
  LocateOffIcon,
  MoveUpIcon,
  MoveDownIcon,
  CornerUpLeftIcon,
  CornerUpRightIcon,
  MoveUpLeftIcon,
  MoveUpRightIcon,
  IterationCwIcon,
  SplitIcon,
  HomeIcon,
  ArrowDownUpIcon,
  MoveUpLeft,
  MoveUpRight,
  Undo2Icon,
};

export default Icons;
